"use strict";
function init()
{
    let characters = document.getElementsByClassName("recapButton");

    for(let char of characters) 
    {
        char.onclick = handleCharacterButton;
    }

    characters[characters.length - 2].onclick = handleBringToTop;
    characters[characters.length - 1].onclick = handleReset;
}

function handleCharacterButton()
{
    let txtBox = document.getElementById("description");
    let nameTxt = document.getElementById("name");
    txtBox.innerHTML = charStories[this.id];
    nameTxt.innerHTML = expandName[this.id];
    document.getElementById("display").scrollIntoView({behavior: 'smooth'});
}

function handleBringToTop()
{
    document.getElementById("header").scrollIntoView({behavior: 'smooth'});
}

function handleReset()
{
    location.reload(true); 
}

window.onload = init;

let charStories = 
{
    "ep1" : "The party is in two groups, Maine & Card and Board. The Maine group was Dream and Okomi, they were at the apartment in Maine, while Vi took Nikko out to go potty. A figure appeared on the TV and started chanting, as lightning struck both of them in the chest. Then the apartment began to shake as it was ripped off the ground and flung through time and space. When things settled they saw their bodies no longer theirs alone—now having another being infused within them. When going outside the top half of a man’s body fell from above them, looking like he was ripped in half. Two guards came by and believed they were the ones who murdered this man. Dream let out their inner Karen on the guards as Okomi went willingly with them to the Town Hall. Group Card and Board consists of Ben, Kody, & Garrett. They were in the middle of a commander battle when Ben summoned Xanathar. The lights began to flicker and people started running out of the shop. As lightning struck through the light fixtures hunting people down. Screams and blood splatter everywhere, as each of them was hit. Then the shop ripped off the ground and was thrown into the new world. When arriving they found out the town was being raided by goblins. Milo the Mercenary gave them weapons to defend themselves. They decided that bunkering down in the bar was the best idea. While in the bar Garrett was having a midlife crisis and was talking to people who weren’t there. Garrett convinced the party that they needed to help protect the people and discovered he could use magic. They all went to the center of town, where Garrett was instantly killed. (Cut to Garrett) Fighting their way together they ran into Okomi and Dream. And was able to kill all of the Goblins. After taking a minute to bury Garrett, they decided to go to the bar. When arriving they saw most of the people getting very drunk after the attack. Seeing Milo and a girl at the table they went over to them. They found out they were not the only people who are from Earth meeting Hannah. Finding out the *Hot* Mayor was kidnapped by the Goblins and together they went to rescue her. After finding a weird glowing cave they were able to kill the goblins and this is where the session was brought to a close.",
    "ep2" : "The party starts in the mystical cave, with a bleeding-out Skyla lying on the ground. Ben managed to bandage her up after Kody decided to heal her. Skyla recognizing the markings told the group that this was an ancient cursed one’s temple and to put their hand on the paw print on the wall. While the party questioned her motives Ben went straight to opening the door. Exposing the Ice Trials. Going through the Wisdom trial quite easily they advanced to the Dexterity Labyrinth trial. Finding out they were on thin Ice they trod carefully and were able to find out the exit. Leading to a big arena, where a mechanized dragon awoke and stood up on its charger. The party using the walls and surroundings jumped the dragon. Beating it sensely they didn’t give it much of a chance to fight back. Destroying it they moved to the last room, which was a laboratory. On the wall laid a blue crystal, the Ice Crystal. Skyla told the party if they manage to collect all 6 crystals they will be able to make a wish. This place was built by Infused people like themselves and is empowered by the crystals. They went back to town saw the carnage, and found out there was someone who studied the Curse who lives in Penrith. After shopping around and finding a strip club and drug store combo. They went to sleep and had joint dreams. Then heading to the town hall the mercenary Milo agreed to accompany them since he has his next job in Penrith.",
    "ep3" : "The party decided to head off to Penrift with Milo. A couple of hours in they got warned about a monster ahead and to turn back. Ignoring the warning, the drawers turned out to be said monster and attacked the party. After they decided to set up for the night. Milo hosted a firewood gathering contest. While struggling to find wood Hannah got jumped by a tiger. After defeating it with Kody’s assistance, Ben won the competition by collecting the most wood. Later on Ben noticed the metal on Milo’s armor. Finding out it is a sending stone to let his mom know he is thinking of her. The party then slept and woke up and continued the walk. When they arrived at the Nile River. Before crossing they notices a yellow light from the distance. Putting a vote, they decided to investigate it. Arriving to another temple, buried underground. The light from the crystal allowed grass to grow in this cavern. Exploring they found a suspicious carpet, underneath lied a lavatory. Finding notes from the last resident, they learned the two of them had infusions like the party. Trying to cure themselves they reached out to the commission. But that backfired, getting their lab burned to the ground causing them to flee. After some time, Micheal transformed fully into a tiger. In hopes for a cure, the scientists reached out to a colleague. He sent an assassin, with a crystal blade. Cutting Micheal’s throat, crystals expanded ripping through his neck. The party found out that the crystal reacts to their Ice crystal. Going above again, in attempt to get the crystal from the air, Hannah threw her basketball. After a few tries she knocked the crystal off, depowering the cavern. After retrieving the healing crystal shard they had an idea to try and revive Garrett, since it has been less than a week since his passing. So everyone turned back and head to town, traveling nonstop. Rescuing Garrett’s decaying body and purifying the “food”. They slept and went back to the trial. Putting the ring on Garrett’s hand and connecting it to the giant crystal near the lake. Garrett heard a voice as he was pulled from the Either. Garrett is Now resurrected. After hearing Michael want Garrett to kill Milo and finding out the scientist seppuku. They left for Penrith, arriving at Jason’s house. Hannah decided she had enough with the party and dipped with Milo. Finding out Jason was captured by thugs, they swiftly killed the thugs.",
    "ep4" : "After all of the robbers had been defeated, Jason realized he had been saved by the Infused. He was very excited that the species he studied his whole life was standing in front of him. After finding out they were looking for a cure, Jason pulled out the Draco Tablet which can locate nearby ruins, and was able to teleport to previously paired ruins. Jason gave his nephew the power crystal to activate it. So the party had to pick it up from him. Going to Hell’s Kitchen, they realized he worked in a “Tiefling Hooters”.  The nephew only being half-tiefling stood out like a sore thumb. He offered the crystal if they could teach him how to be sexy/confident. Where Ben said to the first thing that comes to your mind, don’t overthink it. So he went to try the advice on another table and ended up slapping them hard on the face. Coming back satisfied, he gave the crystal to the party. And the party high-tailed it out of there. Going back to Jason, he installed it and found out only Infused can see what it shows. The tablet is missing 3 chips only letting them use the map and teleport functions. Per the deal, each of them gave up a vile of their blood. He then told them he could make a toxin that connects them to their beast more (Giving an extra skill point). They needed to get pickled Greens, from the grocery store he is banned from, and a blue & Purple flower one for each person. Also offered up, 10 gold for extra flowers and 25 gold per right hand of the guards of the flower. Heading to the grocery store they decided to pull off a heist. To avoid suspension, they decided to buy a couple of things with the pickled Greens and wait 5 minutes between. Everyone made it through without suspicion but Dream who only bought the Greens. But she escaped successfully. Deciding to sleep after their efforts, we had a :sparkles:Dream Sequence :sparkles:. Then heading out to revine they created rope to go down into it.  Ben with help of Garrett’s Car snuck into the cave and picked the flowers. After talking they decided to attack Owl Bears. During the fight, Okami appeared and joined the fight. While Kody was being a good Tank, he spreaded a head out of his shoulder and chest. Successful killing all but one, Dream did the griddy and offered a Scooby snack and with Wild Owl Bear decided to follow her now.",
    "ep5" : "The group manages to cut off the right paw of the 4 Owlbears, butchering 2 of the claws. They then climbed the wall by levitating Kody up and down. They then went over to Jason's house to deliver the materials for the paste. Jason was dissecting some blood and noticed the infusion growing is releasing a magical compound that allows them to use the tech. Jason made the paste, and had them consume it. Everyone by Garrett eat it. Kody grew and inch and a permeant second head, Okami shrank an inch and lost 10 lbs., and Ben had more fur takeover his body. He then gave a research note from his sister who lives near the ruins where they found the tablet in Icemeet. She found an RTC-Chip to repair one of the apps on the tablet. So they started their journey to Icemeet, made it through the Nile, and ran into an infused human who turned into an Oni. He had only been infused for 6 months according to his letter. They then arrived at the Celiso, greeted by the mayor who requested their help in the morning. Garrett & Ben both had dreams, Garrett woke up with a bloody forehead and a giant scar where he was killed prior. He told the group they need to get to Pavv right now. So they left in the morning, ignoring the Mayor. They arrived at the Golden Gate Bridge, when the tablet said there is a ruins nearby. So they took a detour and went onto the toll road. Then jumped off the bridge together to get into the ruins. Went through the first trial "Where is my water", then battled in the "Liquid Spirits Chamber". Where a water spider spirit body slammed into Garrett, 1-hit KOing him. The wolf spirit killed himself to revive Garrett, giving him a warning. The party destroyed the other two forms, and their cores fell onto the ground. Ending the session."
};

let expandName =
{
    "ep1" : "New World",
    "ep2" : "Icy Drugs",
    "ep3" : "Rebirth",
    "ep4" : "Draco Tablet",
    "ep5" : "Garrett Dies again"
};
